from django.conf.urls import patterns, include, url
from django.contrib import admin
from settings import CSS_DIR, JS_DIR, IMG_DIR, LIB_DIR

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'DashBoardView.views.home'),
    url(r'^home/$', 'DashBoardView.views.home'),
    url(r'^detail/\d+/$', 'DashBoardView.views.detail'),
    url(r'get-detail/(?P<vm_id>\d+)/$', 'DashBoardView.views.get_detail'),
    url(r'^settings/$', 'DashBoardView.views.settings'),
    url(r'^saveUserInfo','DashBoardUser.views.saveUserInfo'),
    url(r'^changePassword','DashBoardUser.views.changePassword'),
    url(r'^refreshHomePage/$', 'DashBoardView.views.RefreshHomePage'),
    url(r'^refreshSimplePage/$', 'DashBoardView.views.RefreshSimplePage'),
    url(r'^refreshSimplePageHost/$', 'DashBoardView.views.RefreshSimplePageHost'),
    url(r'^saveVMState/$', 'VirtualMachines.views.VMState'),
    url(r'^helloServer/$', 'VirtualMachines.views.helloServer'),
    url(r'^login/$', 'DashBoardView.views.login'),
    url(r'^logout/$', 'DashBoardView.views.logout'),
    url(r'^apply/$', 'DashBoardView.views.apply'),
    url(r'^audit/$', 'DashBoardView.views.audit'),
    url(r'^get_my_applications', 'Applications.views.get_my_applications'),
    url(r'^get_untreated_applications', 'Applications.views.get_untreated_applications'),
    url(r'^do_apply/$', 'Applications.views.do_apply'),
    url(r'^delete_apply/$', 'Applications.views.delete_apply'),
    url(r'^start_apply/$', 'Applications.views.start_apply'),
    url(r'^stop_apply/$', 'Applications.views.stop_apply'),
    url(r'^savestate_apply/$', 'Applications.views.savestate_apply'),
    url(r'^applications/$', 'DashBoardView.views.applications'),
    url(r'^ratify_application', 'Applications.views.ratify_application'),
    url(r'^refuse_application', 'Applications.views.refuse_application'),
    url(r'^ratify_all', 'Applications.views.ratify_all'),
    url(r'refuse_all', 'Applications.views.refuse_all'),
    url(r'^myVMs', 'DashBoardView.views.myVMs'),
    url(r'^get_my_VMs', 'VirtualMachines.views.get_my_VMs'),
    url(r'^vmHost_reply', 'Applications.views.vmHost_reply'),
    url(r'^css/(?P<path>.*)', 'django.views.static.serve', {'document_root': CSS_DIR}),
    url(r'^js/(?P<path>.*)', 'django.views.static.serve', {'document_root': JS_DIR}),
    url(r'^img/(?P<path>.*)', 'django.views.static.serve', {'document_root': IMG_DIR}),
    url(r'^lib/(?P<path>.*)', 'django.views.static.serve', {'document_root': LIB_DIR}),
)
